// export const CREATE_CONTACT = "CREATE_CONTACT";
export const LOAD_CONTACTS_SUCCESS = "LOAD_CONTACTS_SUCCESS";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const CREATE_CONTACT_SUCCESS = "CREATE_COURSE_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const DELETE_CONTACT_OPTIMISTIC = "DELETE_CONTACT_OPTIMISTIC";
export const LOAD_SEARCH_SUCCESS = "LOAD_SEARCH_SUCCESS";